#!/usr/bin/env node
/* FinFlow deterministic audit — zero dependencies.
 * Run:  node audit.js
 * Writes AUDIT_CODE.md next to this file and prints a summary.
 * Pure static analysis (regex + file scans). No judgment, fully reproducible.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const findings = [];   // {sev, id, title, detail, hits:[{file,line,text}]}
function add(sev, id, title, detail, hits) { findings.push({ sev, id, title, detail, hits: hits || [] }); }

// ── file helpers ──────────────────────────────────────────────────────────
function walk(dir, out = []) {
  for (const name of fs.readdirSync(dir)) {
    if (name === 'node_modules' || name === '.git') continue;
    const p = path.join(dir, name);
    const st = fs.statSync(p);
    if (st.isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
}
const ALL = walk(ROOT);
const CODE = ALL.filter(f => /\.(js|jsx|ts|html)$/.test(f) && !/\.min\.js$/.test(f));
function read(f) { try { return fs.readFileSync(f, 'utf8'); } catch { return ''; } }
function rel(f) { return path.relative(ROOT, f).replace(/\\/g, '/'); }

// grep: return [{file,line,text}] across a file list
function grep(re, files) {
  const hits = [];
  for (const f of files) {
    const lines = read(f).split(/\r?\n/);
    for (let i = 0; i < lines.length; i++) {
      if (re.test(lines[i])) hits.push({ file: rel(f), line: i + 1, text: lines[i].trim().slice(0, 160) });
      re.lastIndex = 0;
    }
  }
  return hits;
}
function fileByName(name) { return ALL.find(f => rel(f) === name || path.basename(f) === name); }
function has(str, sub) { return str.indexOf(sub) !== -1; }

// ── CHECK 1: generated bundle vs its wiring sources (real drift) ────────────
// The served file is public/finflow-bundle.js (non-minified), generated by
// bundle.js by concatenating the 10 wiring sources. Real drift = the committed
// bundle no longer equals a fresh concatenation of its sources (someone edited a
// wiring source without running `node bundle.js`). The old .min.js files are not
// served and have been removed, so we no longer compare against them.
(function () {
  const SOURCES = [
    'finflow-api.js', 'finflow-api-wiring.js', 'finflow-api-wiring-medium.js',
    'finflow-api-wiring-final.js', 'finflow-api-wiring-stubs.js', 'finflow-api-wiring-final5.js',
    'finflow-api-wiring-pages.js', 'finflow-api-wiring-extra.js', 'finflow-api-wiring-dashboard.js',
    'finflow-api-wiring-postgres.js',
  ];
  const outF = fileByName('public/finflow-bundle.js');
  if (!outF) { add('HIGH', 'BUNDLE-MISSING', 'public/finflow-bundle.js missing', 'Cannot verify sync.', []); return; }
  const srcFiles = SOURCES.map(f => fileByName('public/' + f) || fileByName(f));
  if (srcFiles.some(f => !f)) { add('HIGH', 'BUNDLE-MISSING', 'A wiring source is missing', 'Cannot rebuild bundle to verify.', []); return; }
  // Reconstruct exactly like bundle.js (same separators) and compare content-only.
  const rebuilt = srcFiles.map((f, i) => `/* ── ${SOURCES[i]} ── */\n${read(f)}\n`).join('\n;\n');
  const norm = s => s.replace(/\r\n/g, '\n');
  if (norm(read(outF)) !== norm(rebuilt)) {
    add('CRITICAL', 'BUNDLE-STALE', 'public/finflow-bundle.js is OUT OF SYNC with its wiring sources',
      'A wiring source was edited without regenerating the bundle — the served bundle would not reflect the edit. '
      + 'Run: node bundle.js (or rely on the prestart / pre-commit guards).', []);
  } else {
    add('INFO', 'BUNDLE-OK', 'finflow-bundle.js is in sync with its sources',
      'A fresh concatenation of the 10 wiring sources matches the committed bundle (line-ending-normalized).', []);
  }
  // Regeneration guard present?
  const pkg = fileByName('package.json');
  if (pkg) {
    const j = JSON.parse(read(pkg));
    const scripts = j.scripts || {};
    if (!scripts.prestart && !scripts.build)
      add('HIGH', 'NO-BUILD', 'No prestart/build guard regenerates the bundle',
        'Nothing rebuilds finflow-bundle.js on deploy; source edits can silently fail to ship.', []);
  }
})();

// ── CHECK 2: report endpoints entity scoping ───────────────────────────────
(function () {
  const sf = fileByName('server.js'); if (!sf) return;
  const src = read(sf); const lines = src.split(/\r?\n/);
  // find app.<verb>('/api/...') handlers and inspect their body for matchEnt / entity filter
  const routeRe = /app\.(get|post|put|delete)\(\s*'(\/api\/[^']+)'/;
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(routeRe);
    if (!m) continue;
    // grab handler body (until next top-level app.<verb>( or 400 lines)
    let body = '', depth = 0, started = false;
    for (let j = i; j < Math.min(i + 120, lines.length); j++) {
      body += lines[j] + '\n';
      if (j > i && routeRe.test(lines[j])) break;
    }
    const path_ = m[2];
    const readsData = /db\.allByUser\(|pool\.query\(/.test(body);
    const usesInvoicesOrExpenses = /allByUser\('(invoices|expenses)'/.test(body);
    const scoped = /matchEnt|entity_id\s*(==|===|IS NULL|=)|req\.entityId/.test(body);
    if (usesInvoicesOrExpenses && !scoped && /reports|balance|cash-flow|profit-loss/.test(path_)) {
      add('HIGH', 'NO-ENTITY-SCOPE', `${path_} reads invoices/expenses without entity scoping`,
        'Aggregates across all of a user\'s entities; will not reconcile with entity-scoped dashboard.',
        [{ file: 'server.js', line: i + 1, text: lines[i].trim() }]);
    }
  }
})();

// ── CHECK 3: FX unrealised_gain_loss read-but-never-written ─────────────────
(function () {
  const reads = grep(/unrealised_gain_loss/, CODE);
  const writes = grep(/unrealised_gain_loss\s*=|SET\s+unrealised_gain_loss|unrealised_gain_loss[^)]*\bVALUES\b/i, CODE)
    .filter(h => /=|VALUES|SET/.test(h.text) && !/SUM\(|CASE WHEN/.test(h.text));
  if (reads.length && writes.length === 0)
    add('HIGH', 'FX-UNREALISED-DEAD', 'unrealised_gain_loss is read/summed/displayed but never computed',
      'Only a DEFAULT 0 exists; no code path assigns it. Open FX positions always report $0 unrealised P/L.',
      reads.slice(0, 6));
})();

// ── CHECK 4: fabricated / mock data ────────────────────────────────────────
(function () {
  const email = grep(/@company\.com|@example\.com|noreply@finflow\.app/, CODE);
  if (email.length) add('MEDIUM', 'FABRICATED-EMAIL', 'Synthesized email addresses in code',
    'Emails constructed from names / hardcoded rather than real data.', email.slice(0, 8));
  const rnd = grep(/Math\.random\(/, CODE);
  if (rnd.length) add('LOW', 'MATH-RANDOM', 'Math.random() usage (verify none feeds financial values)',
    'Confirm each is cosmetic (animation/color), not data.', rnd.slice(0, 12));
  const todo = grep(/\b(TODO|FIXME|HACK|XXX)\b/, CODE);
  if (todo.length) add('LOW', 'TODO', `${todo.length} TODO/FIXME/HACK markers`, 'Unfinished work markers.', todo.slice(0, 15));
})();

// ── CHECK 5: hardcoded secrets / test keys / localhost ─────────────────────
(function () {
  const secrets = grep(/sk_live_|sk_test_|whsec_[A-Za-z0-9]{6,}|AKIA[0-9A-Z]{12,}|-----BEGIN|password\s*[:=]\s*['"][^'"]{3,}/, CODE)
    .filter(h => !/\.env\.example|process\.env|placeholder|xxxx|your_/i.test(h.text));
  if (secrets.length) add('CRITICAL', 'HARDCODED-SECRET', 'Possible hardcoded secret/credential', 'Review immediately.', secrets);
  const local = grep(/https?:\/\/localhost|127\.0\.0\.1/, CODE).filter(h => !/localhost:\$\{|PORT|default|dev/i.test(h.text));
  if (local.length) add('LOW', 'LOCALHOST', 'Hardcoded localhost/127.0.0.1 references', 'Verify these are dev-only fallbacks.', local.slice(0, 10));
})();

// ── CHECK 6: multiple writers to dashboard KPI element ids ─────────────────
(function () {
  for (const id of ['d-rev', 'd-exp', 'd-profit']) {
    const re = new RegExp(`(getElementById\\(['"]${id}['"]\\)|['"]${id}['"]\\s*,)`);
    const hits = grep(re, CODE).filter(h => /set\(|textContent|innerHTML|getElementById/.test(h.text));
    const files = [...new Set(hits.map(h => h.file))];
    if (hits.length >= 3)
      add('HIGH', 'KPI-MULTIWRITE-' + id, `'${id}' is written from ${hits.length} places (${files.length} files)`,
        'Multiple independent KPI writers risk divergent formulas for the same on-screen number.', hits.slice(0, 8));
  }
})();

// ── CHECK 7: env var references vs .env.example ────────────────────────────
(function () {
  const used = new Set();
  for (const h of grep(/process\.env\.[A-Z0-9_]+/, CODE)) {
    const mm = h.text.match(/process\.env\.([A-Z0-9_]+)/g) || [];
    mm.forEach(x => used.add(x.replace('process.env.', '')));
  }
  const ex = fileByName('.env.example');
  const declared = new Set();
  if (ex) read(ex).split(/\r?\n/).forEach(l => { const m = l.match(/^([A-Z0-9_]+)\s*=/); if (m) declared.add(m[1]); });
  const builtin = new Set(['NODE_ENV', 'PORT', 'RAILWAY_DEPLOYMENT_ID']);
  const undoc = [...used].filter(v => !declared.has(v) && !builtin.has(v)).sort();
  if (undoc.length) add('LOW', 'ENV-UNDOCUMENTED', 'Env vars used in code but absent from .env.example',
    undoc.join(', '), []);
})();

// ── CHECK 8: divide-by-zero / cents-dollars sanity ─────────────────────────
(function () {
  const div = grep(/\/\s*(revenue|total|basis|count|units_purchased|denominator)\b/, CODE)
    .filter(h => !/Math\.max\(|>\s*0\s*\?|\|\|\s*1|:\s*0/.test(h.text));
  if (div.length) add('LOW', 'DIV-GUARD', 'Division without an obvious zero-guard (verify)',
    'Confirm denominators cannot be 0.', div.slice(0, 12));
  const cents = grep(/amount_total|amount_received|\* 100|\/ 100|billedCents|feeCents/, CODE.filter(f => /server\.js|routes/.test(f)));
  if (cents.length) add('INFO', 'CENTS', 'Cents/dollars conversion sites (manual review recommended)',
    'Stripe amounts are in cents; verify every ×100 / ÷100 boundary.', cents.slice(0, 10));
})();

// ── OUTPUT ─────────────────────────────────────────────────────────────────
const order = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3, INFO: 4 };
findings.sort((a, b) => order[a.sev] - order[b.sev]);
const counts = findings.reduce((m, f) => (m[f.sev] = (m[f.sev] || 0) + 1, m), {});

let md = `# FinFlow — Automated Code Audit (audit.js)\n\n`;
md += `Generated: ${new Date().toISOString()}\n\n`;
md += `Scanned ${CODE.length} source files (excl. node_modules, excl. .min.js).\n\n`;
md += `**Totals:** ` + ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'].map(s => `${counts[s] || 0} ${s}`).join(' · ') + `\n\n---\n\n`;
for (const f of findings) {
  md += `### [${f.sev}] ${f.id} — ${f.title}\n\n${f.detail}\n\n`;
  if (f.hits.length) {
    md += f.hits.map(h => `- \`${h.file}:${h.line}\`  ${h.text.replace(/`/g, "'")}`).join('\n') + '\n\n';
  }
}
fs.writeFileSync(path.join(ROOT, 'AUDIT_CODE.md'), md);

// console summary
console.log('\nFinFlow automated audit complete → AUDIT_CODE.md');
console.log('Totals: ' + ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'].map(s => `${counts[s] || 0} ${s}`).join('  '));
console.log('');
for (const f of findings) if (f.sev !== 'INFO') console.log(`  [${f.sev}] ${f.id} — ${f.title}`);
console.log('');
